import type { Metadata } from "next";
import { Jost , Comforter } from "next/font/google";
import "./globals.css";

export const jost = Jost({ subsets: ["latin"]})
export const comforter = Comforter({
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Portfolio | Jatin Saini",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>{children}</body>
    </html>
  );
}
